version: '2'
services:


  idp:
    environment:
      - NODE_ENV=docker
    build: ./idp
    depends_on:
      - redis
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - sp
    extra_hosts:
     - "rails-jobs.docker:192.168.99.100"

  sp:
    environment:
      - RAILS_ENV=test
      - RACK_ENV=test
      - DATABASE_PORT_3306_TCP_ADDR=mysql
      - LANG=en_US.UTF-8
      - RAILS_SERVE_STATIC_FILES=enabled
    build: ./sp
    command: bash -c "sleep 5; rake db:drop; rake db:create; rake db:migrate; rake db:seed;bundle exec rails s -p 3001 -b 0.0.0.0"
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "3001:3001"
    expose:
      - "3001"
    extra_hosts:
     - "rails-jobs.docker:192.168.99.100"

  converse:
    environment:
      - NODE_ENV=integration
      #- MONGO_URL=mongodb:27017/converse_test
      #- MONGO_URL=mongodb://127.0.0.1:27017/converse_test
    build: ./converse
    ports:
      - "3030:3030"
    expose:
      - "3030"
    links:
      - sp
    extra_hosts:
     - "rails-jobs.docker:192.168.99.100"

  redis:
    image: redis
    restart: always

  mysql:
    image: mysql:5.5
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: railsjobs_test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
